In [1]:

# importing Python library
import numpy as np

In [2]:
# define Unit Step Function
def unitStep(v):
    if v >= 0:
        return 1
    else:
        return 0

In [3]:
# design Perceptron Model
def perceptronModel(x, w, b):
    v = np.dot(w, x) + b
    y = unitStep(v)
    return y

In [4]:
# OR Logic Function
# w1 = 1, w2 = 1, b = -0.5
def OR_logicFunction(x):
    w = np.array([1, 1])
    b = -0.5
    return perceptronModel(x, w, b)

In [5]:
# testing the Perceptron Model
test1 = np.array([0, 0])
test2 = np.array([0, 1])
test3 = np.array([1, 0])
test4 = np.array([1, 1])

In [7]:
print("OR({}, {}) = {}".format(0, 0, OR_logicFunction(test1)))
print("OR({}, {}) = {}".format(0, 1, OR_logicFunction(test2)))
print("OR({}, {}) = {}".format(1, 0, OR_logicFunction(test3)))
print("OR({}, {}) = {}".format(1, 1, OR_logicFunction(test4)))

OR(0, 0) = 0
OR(0, 1) = 1
OR(1, 0) = 1
OR(1, 1) = 1


or alternative r akta way dilam

In [8]:
import numpy as np






In [9]:
weight = np.array([1,1])
bias = -0.5
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

In [10]:
def OR_perceptron(x, weight, bias):
    
    fx = np.dot(weight, x)  + bias
    
    if fx >= 0:
        return i, 1
    else:
        return i, 0

In [12]:

for i in inputs:
    print(OR_perceptron(i, weight, bias))

(array([0, 0]), 0)
(array([0, 1]), 1)
(array([1, 0]), 1)
(array([1, 1]), 1)
